name = "The Distant Isles"
author = "seep_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57e3ed8911969431f488645331376d3e7aa6f5cbf261a19de88a56927d2d2608"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
