name = "The Distant Isles"
author = "seep_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de6b84266d7103902a162aa37506bfbcfb095b98aafd29e1c44b4a450020cd76"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
