name = "The Distant Isles"
author = "seep_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9cdc063e3845c9a5b8596cdd2d1f43163314ccff58c8e56d24200dbf3af6505"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
